"""Tests for lws.terraform.override -- override file generation."""

from __future__ import annotations

from pathlib import Path

import pytest

from lws.terraform.override import MARKER_COMMENT, OVERRIDE_FILENAME, generate_override


class TestGenerateOverride:
    """Tests for the generate_override function."""

    def test_generates_override_file(self, tmp_path: Path) -> None:
        """Generate override file with correct content and endpoint URLs."""
        port = 3000
        override_path = generate_override(port, tmp_path)

        assert override_path.exists()
        assert override_path.name == OVERRIDE_FILENAME

        content = override_path.read_text()
        assert MARKER_COMMENT in content

        # Verify endpoint URLs (base port + 1 through 13)
        assert f"http://localhost:{port + 1}" in content  # dynamodb
        assert f"http://localhost:{port + 2}" in content  # sqs
        assert f"http://localhost:{port + 3}" in content  # s3
        assert f"http://localhost:{port + 4}" in content  # sns
        assert f"http://localhost:{port + 5}" in content  # cloudwatchevents
        assert f"http://localhost:{port + 6}" in content  # stepfunctions
        assert f"http://localhost:{port + 7}" in content  # cognitoidp
        assert f"http://localhost:{port + 8}" in content  # apigateway
        assert f"http://localhost:{port + 9}" in content  # lambda
        assert f"http://localhost:{port + 10}" in content  # iam
        assert f"http://localhost:{port + 11}" in content  # sts
        assert f"http://localhost:{port + 12}" in content  # ssm
        assert f"http://localhost:{port + 13}" in content  # secretsmanager

        # Verify both V1 and V2 API Gateway endpoints point to same port
        assert f'apigateway       = "http://localhost:{port + 8}"' in content
        assert f'apigatewayv2     = "http://localhost:{port + 8}"' in content

    def test_overwrites_lws_generated_file(self, tmp_path: Path) -> None:
        """Overwrite existing LWS-generated override file."""
        override_path = tmp_path / OVERRIDE_FILENAME
        override_path.write_text(f"{MARKER_COMMENT}\nOld content")

        port = 4000
        result_path = generate_override(port, tmp_path)

        assert result_path == override_path
        content = override_path.read_text()
        assert "Old content" not in content
        assert f"http://localhost:{port + 1}" in content

    def test_refuses_to_overwrite_user_file(self, tmp_path: Path) -> None:
        """Raise FileExistsError when trying to overwrite user-created file."""
        override_path = tmp_path / OVERRIDE_FILENAME
        override_path.write_text('# User-created file\nprovider "aws" {}')

        with pytest.raises(FileExistsError) as exc_info:
            generate_override(3000, tmp_path)

        assert OVERRIDE_FILENAME in str(exc_info.value)
        assert "not generated by LWS" in str(exc_info.value)
