plugins {
    id 'java'
}

group = 'com.example'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenLocal()
    mavenCentral()
}

def awsSdkVersion = '2.26.0'
def cucumberVersion = '7.18.0'

dependencies {
    implementation platform("software.amazon.awssdk:bom:${awsSdkVersion}")
    implementation 'software.amazon.awssdk:sfn'
    implementation 'software.amazon.awssdk:dynamodb'
    implementation 'software.amazon.awssdk:sqs'

    testImplementation files('/tmp/gradle-build-lws-java-sdk/libs/local-web-services-java-sdk-0.2.2.jar')
    testImplementation files('/tmp/gradle-build-lws-java-core/libs/lws-java-core-0.1.0.jar')
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-picocontainer:${cucumberVersion}"
    testImplementation 'org.junit.platform:junit-platform-suite'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

sourceSets {
    test {
        resources {
            srcDir '../../specification/example'
        }
    }
}

test {
    useJUnitPlatform()
    systemProperty 'cucumber.junit-platform.naming-strategy', 'long'
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}
